### ISSUE TITLE
Release automation

### ISSUE THREAD

**Issue by JohnTitor** [rust-lang/rust-semverver#300]
Currently, I do release manually. But I'd like to do continuous release as it depends on a specific nightly version, and this could be done by GHA, I think.

**Comment by dario23** [comment]
what should trigger a new release? merged commit that changes the `rust-toolchain` file? or just any merged commit? nightly if anything was merged that day? is there a way to tell bors to trigger a release, similar to the `rollup` arg? otherwise i guess we can build a github action on a label `do-release` that triggers a release once a pull request with that label gets merged.

**Comment by JohnTitor** [comment]
bors doesn't handle any release but merges PRs. I think we can listen to adding a git tag event and trigger the workflow. More automation e.g. auto-incrementing version number would be possible but it's overkill here, I feel. I just don't want to do a release on my local (at least for now).
Note that this will need us to set the crates.io token, I'm going to ask the infra team once it's ready.
